# Generated by Django 4.2.27 on 2026-01-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='cleaned_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleaned/'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
