# Generated by Django 4.2.27 on 2026-01-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_uploadimage_cleaned_image_uploadimage_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
